<div class="container">    
    <div style="margin-top:50px;" class="col-md-8 col-md-offset-2">                    
        <div class="panel panel-info" >
            <div class="panel-heading">
                <div class="panel-title">Cadastre-se, e aproveite as vantagens da nossa plataforma</div>
                <div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="/">Faça Login!</a></div>
            </div>     
            <div style="padding-top:30px" class="panel-body" >
                <?php echo $this->form()->openTag($form); ?>    
                <div class="form-horizontal" role="form">
                    <div class="row">
                        <div class="col-md-12">
                            <div style="margin-bottom: 25px" class="input-group form-group-cadastro">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                <?php echo $this->formRow($form->get('nome')); ?>                                 
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div style="margin-bottom: 25px" class="input-group form-group-cadastro">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                                <?php echo $this->formRow($form->get('email')); ?>
                            </div>
                            <div id="email-sucess-message" class="alert alert-success alert-dismissable">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <strong>Muito Bem!</strong> Este e-mail ainda não foi cadastrado em nossa base de dados.
                            </div>
                            <div id="email-error-message" class="alert alert-danger alert-dismissable">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <strong>OPS!</strong> Um Usuário com este e-mail já consta em nossa base de dados.
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div style="margin-bottom: 25px" class="input-group form-group-cadastro-left">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                <?php echo $this->formRow($form->get('senha')); ?>                                 
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div style="margin-bottom: 25px" class="input-group form-group-cadastro ">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                <?php echo $this->formRow($form->get('confirmarsenha')); ?>
                            </div>
                        </div>
                    </div>
                    <div style="margin-top:10px" class="form-group">
                        <div class="col-sm-4 controls">
                            <?php echo $this->formRow($form->get('cadastro')); ?>
                        </div>
                    </div>    
                </div>     
                <?php echo $this->form()->closeTag($form); ?>
            </div>                     
        </div>  
    </div>
</div>
